before_commands:
    - "composer install --dev --no-interaction --no-suggest --no-scripts --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: ./bin/phpunit
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor", "bin"]
    php_cs_fixer:
        enabled: true
        config: { level: PSR2 }
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor", "bin"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor", "bin"]
    sensiolabs_security_checker: true

