filter:
    paths:
        - 'src/*'

before_commands:
    - "composer install --dev --no-interaction --no-suggest --no-scripts --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_code_coverage:
        enabled: true
        test_command: ./bin/phpunit
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true

build:
    tests:
        override:
            -
                command: './bin/phpunit --coverage-clover=coverage-clover'
                coverage:
                    file: 'coverage-clover'
                    format: 'clover'
